In [14]:
import networkx as nx
g = nx.Graph()

g.add_nodes_from([0,1,2, 3,4,5])

g.add_edges_from([(1, 2), (1, 3), (2,3), (3,1), (4,5), (1,4)])

In [15]:
a1 = nx.adjacency_matrix(g)

In [16]:
a1= nx.to_numpy_matrix(g)
# https://networkx.org/documentation/stable/reference/generated/networkx.convert_matrix.to_numpy_matrix.html


In [17]:
a1

matrix([[0., 0., 0., 0., 0., 0.],
        [0., 0., 1., 1., 1., 0.],
        [0., 1., 0., 1., 0., 0.],
        [0., 1., 1., 0., 0., 0.],
        [0., 1., 0., 0., 0., 1.],
        [0., 0., 0., 0., 1., 0.]])

In [ ]:
# algorithm 1 (cycle bases suurvey)
T = spanning_tree(g)

cycles = []
for i in range(v):
    # non zero vector S_i 
    # cehck S_i(e) =0 for e in T
    for e in T:
        sie = Si(e)
        if sie!=0: 
            print("Another vector Si")
# 

# Algorithm in 5.7.3 : replace line 4 of Algo 1 with find min wt isometric circuit C_i with <C_i, S_i> != 0

# pg 52: circuit is isometric if for any u v on it, the p_{uv} best path conn. them is contained in it;
# pg 49 to 51: compuute best paths

def maintain_basis_orthog_space():
    # initialize S_j 
    S= []
    for j in range(v):
        S_j = np.zeros(m)
        
        for i in range(m): # number of edges m
            if i==j:
                S_j[i] = 1# set to 1 if i=j
        S[j] = S_j
    for i in range(v):
        # compuute min wt cycle C_i in H with <C_i, S_i> neq 0
        

# compute min wt cycle from H
def min_wt_cycle(H, S):
    # first check if <C_i , S_i> neq 0
    min_wt_cycle_set= []
    for h in H:
        if np.dot(h, S) != 0:
            # find weight
            w_h = add_weights(h)

def add_weights(h):
    

In [ ]:
# quotient graph , by triangles

# https://networkx.org/documentation/stable/tutorial.html

# https://www.kite.com/python/docs/networkx.quotient_graph

all_cliques= nx.enumerate_all_cliques(g)

triad_cliques=[x for x in all_cliques if len(x)==3 ]

Q = nx.quotient_graph(g, is_triangle)



In [21]:
# quotient graph, by cycles ? cliques?

cycle_basis = nx.cycle_basis(g, 0) # 0 is root


In [22]:
cycle_basis

[[2, 3, 1]]

In [8]:
# https://stackoverflow.com/questions/57661314/fastest-way-to-find-all-cycles-of-length-n-containing-a-specified-node-in-a-dire

def findPaths(G,u,n):
    if n==0:
        return [[u]]
    paths = [[u]+path for neighbor in G.neighbors(u) for path in findPaths(G,neighbor,n-1)]
    return paths

def find_cycles(G,u,n):
    paths = findPaths(G,u,n)
    return [tuple(path) for path in paths if (path[-1] == u) and sum(x ==u for x in path) == 2]

#cycles = find_cycles(DG,'A',4)


In [18]:
cyc1 = find_cycles(g, 0, 5)

In [19]:
cyc1

[]

In [20]:
findPaths(g, 0, 5)

[]

In [ ]:
# touching number of cycles in the cycle basis

# https://networkx.org/documentation/stable/_modules/networkx/algorithms/cycles.html

touching_num = 0
touching_edges = []

for cycle in cycle_basis:
    # look up edges with vertices from cycle
    for v in cycle:
        v_row = adj_mat[v]
        output = [idx for idx, element in enumerate(v_row) if element ==1]
        for edge_vertex in output:
            if edge_vertex in cycle:
                # do not add
            else:
                # add
                touching_edges.append((v, edge_vertex))
                touching_num = touching_num + 1
                
                

In [38]:
# https://www.kite.com/python/answers/how-to-find-the-index-of-list-elements-that-meet-a-condition-in-python

a_list = [0, 1, 1, 0, 1, 0]

output = [idx for idx, element in enumerate(a_list) if element ==1]
print(output)

[1, 2, 4]


In [ ]:
# touching nuumber (pg 26)

max_n = 10 
# t_n of n cycle : range of n 
for n in range(max_n):
    # any cycles with length n
    for u in range(nvertices):
        cycs = find_cycles(G, u, n)
        

In [2]:
import random
list1 = [1,2,3,4,5,6,7,8,9]
random.choices(list1, k=3)

[4, 6, 4]

https://courses.engr.illinois.edu/cs374/fa2020/lec_prerec/18/18_2_2_0.pdf 

hop based  recursion
fix source s (assume all nodes can be reached by s in G)

d(v, k) : shortest walk length from s to v using at most k edges ( dist(s,v) = d(v, n-1) ) 

recursion:
d(v,k) = min $\begin{cases}  min_{ u \in V} ( d(u, k-1) + \ell(u,v))  \\ d(v,k-1) \end{cases}$ 



https://www.quora.com/Is-it-possible-to-use-the-powers-of-an-adjacency-matrix-to-compute-the-shortest-paths-BFS-would-compute 


In [ ]:
# build hopset, https://www.cc.gatech.edu/~rpeng/CS7510_F19/Nov19Hopset.pdf

# pick sqrt(n) random vertices -> S

n=10
sn = np.sqrt(n) 
sn_cap = np.ceil(sn)

S = random.choices(vertices, k=sn_cap)

# compute shortest path from those vertices to every other node up to sqrt(n) hops

# hop-based Bellman Ford algorithm


# Compute all pairs shortest path between vertices in S (using matrix powering)


# https://resources.mpi-inf.mpg.de/departments/d1/teaching/ss12/AdvancedGraphAlgorithms/Slides14.pdf
# fast matrix mult -> all pairs shortest path

# n power of matrix gives distances by paths that use at most k edges

In [6]:
# run bellman ford uup to k steps 
import sys

def bellmanford(vertices, edges, source, k):
    distance = [] # list of size n
    predecessor =[] # list of size n
    
    # initialize graph
    for v in range(n):
        distance[n] = sys.maxsize
        predecessor[v] = None
    
    # relax edges repeatedly : |v| -1 times 
    for j in range(k):
        for e in edges:
            wt = edges[e]
            if distance[u] != sys.maxsize and distance[u] + wt < distance[v]:
                distance[v] = distance[u] + wt
                predecessor[v] = u
    # check for neg wt cycles
    
    return distance, predecessor
                

In [10]:
import numpy as np
adj_mat = np.array([[0,1,0,0],[1,0,1,0], [0,1,0,1], [0,0,1,0]])

In [16]:
k=1

In [17]:
# n power of matrix gives distances by paths that use at most k edges

matpow = adj_mat
for i in range(k):
    matpow = np.matmul(matpow, adj_mat)

print(matpow)

# check for entry in column  : k+1 length path

[[1 0 1 0]
 [0 2 0 1]
 [1 0 2 0]
 [0 1 0 1]]


In [4]:
import sys
val1 = sys.maxsize

In [5]:
val1==sys.maxsize

True

In [18]:
# https://en.wikipedia.org/wiki/Homomorphism_density

In [ ]:
# near-homomorphism or homo - other factor 

# check for homomorphism structure between graphs


In [ ]:
# transform graph -> homomorphisms?



In [1]:
row = [0, 4, 3, 0, 0, 1]
res = [idx for idx, val in enumerate(row) if val != 0]

Step_k graph:
it has same vertices as G, and distinct vertices are adjacent iff there is some walk of length k between them in G. 

In [ ]:
# Step_k graph of G 

def step_k(G, k):
    #  take k-th power and check for entry in coluumn
    matpow = adj_mat
    for i in range(k):
        matpow = np.matmul(matpow, adj_mat)
    # return this matpow with nonzero entries equal 1 
    
    # edge list 
    edge_list = []
    edge1= 0
    for row in matpow:
        # check entries equal 1
        res = [idx for idx, val in enumerate(row) if val != 0]
        for r in res:
            edge_list.append((edge1, r))
            edge_list.append((r, edge1))
        edge1 = edge1+ 1
    
    return edge_list
    

Def. homomorphism density w.r.t. graph $H$: 

$t(H, G) = | hom(H,G)| / |V(G)|^{|V(H)|}

where $hom(H,G)$ is the set of graph homomorphisms / adjacency preserving maps from H to G.

triangle density: $\int_0^1 \int_0^1 \int_0^1 w_g(u_1, u_2) w_g ( u_2, u_3) w_g(u_3, u_1) du_1 du_2 du_3$

k-clique density:  ( k = 4)


$\int_0^1 \int_0^1 \int_0^1 \int_0^1 w_g(u_1, u_2) w_g ( u_2, u_3) w_g(u_3, u_1) w_g(u_1,u_4) w_g(u_2, u4) w_g(u_3, u_4) du_1 du_2 du_3 du_4 $

idea: count homomorphisms from hypergraph to non-hypergraph?

A graph homomorphism is a mapping between two graphs that respects their structure: a function $\phi: V(G) \rightarrow V(H)$ from G to H if preserves edges; for edge [u,v] of G, $[\phi(u), \phi(v)]$ is an edge of H. 

https://mast.queensu.ca/~ctardif/articles/ghss.pdf 

Many results in extremal graph theory can be described by inequalities involving homomorphism densities associated to a graph. The following are a sequence of examples relating the density of triangles to the density of edges.

Density can also be interpreted as the probability that a map from the vertices of H to the vertices of G chosen uniformly at random is a graph homomorphism


In [ ]:
# graph physics - informed NN

class HFMI(object): # hidden fluid mechanics ice

    def __init__(self, x_data, y_data, u_data, v_data, s_data, h_data,b_data,x_eqns, y_eqns, layers, batch_size):
    
        self.layers = layers
        self.batch_size = batch_size

        # data
        [self.x_data, self.y_data, self.u_data, self.v_data, self.s_data, self.h_data, self.b_data] = [x_data, y_data, u_data, v_data, s_data, h_data, b_data]
        [self.x_eqns, self.y_eqns] = [x_eqns, y_eqns]


        # change above to x, y, u,v,s,h ,b 
        [self.x_data_tf, self.y_data_tf, self.u_data_tf, self.v_data_tf, self.s_data_tf, self.h_data_tf, self.b_data_tf]  = [tf.placeholder(tf.float32, shape=[None, 1]) for _ in range(7)]
        [self.x_eqns_tf, self.y_eqns_tf] = [tf.placeholder(tf.float32, shape=[None, 1]) for _ in range(2)]

        # physics uninformed NNs 
        self.net_uvshb = neural_net(self.x_data, self.y_data, layers = self.layers)

        [self.u_data_pred,self.v_data_pred, self.s_data_pred, self.h_data_pred, self.b_data_pred] = self.net_uvshb(self.x_data_tf, self.y_data_tf)

        # physics informed NNs
        [self.u_eqns_pred, self.v_eqns_pred, self.s_eqns_pred, self.h_eqns_pred, self.b_eqns_pred] = self.net_uvshb(self.x_eqns_tf, self.y_eqns_tf)

        [self.e1_eqns_pred,self.e2_eqns_pred, self.e3_eqns_pred] = IceSheet2D(self.u_eqns_pred,
                                                      self.v_eqns_pred,
                                                      self.s_eqns_pred,
                                                      self.h_eqns_pred,
                                                      self.b_eqns_pred,
                                                      self.x_eqns_tf,
                                                      self.y_eqns_tf)

        self.loss = mean_squared_error(self.u_data_pred, self.u_data_tf) + mean_squared_error(self.v_data_pred, self.v_data_tf)+ mean_squared_error(self.s_data_pred, self.s_data_tf) + mean_squared_error(self.h_data_pred, self.h_data_tf)+ mean_squared_error(self.b_data_pred, self.b_data_tf) + mean_squared_error(self.e1_eqns_pred, 0.0) + mean_squared_error(self.e2_eqns_pred, 0.0) + mean_squared_error(self.e3_eqns_pred, 0.0) 
        self.learning_rate = tf.placeholder(tf.float32, shape=[])
        self.optimizer = tf.train.AdamOptimizer(learning_rate = self.learning_rate)
        self.train_op = self.optimizer.minimize(self.loss)

        self.sess = tf_session()

In [ ]:
# quotient graph , by triangles

# https://networkx.org/documentation/stable/tutorial.html

# https://www.kite.com/python/docs/networkx.quotient_graph

all_cliques= nx.enumerate_all_cliques(g)

triad_cliques=[x for x in all_cliques if len(x)==3 ]

Q = nx.quotient_graph(g, is_triangle)



In [ ]:
# quotient graph, by cycles ? cliques?

cycle_basis = nx.find_cycle(g, orientation="ignore")

all_cliques= nx.enumerate_all_cliques(g)

In [ ]:
# probabilistic low diameter decomp's



In [ ]:
# https://arxiv.org/pdf/1309.3545.pdf: Improved Parallel Algos for Spanners and Hopsets

# graph decomposition called Exponential Start Time Clustering (Algo. 1)

def exp_start_time_cluster(g, beta, distances):
    # clusters
    clusters = {}
    # for eac vertex
    n_ver = len(g)
    deltas = {}
    dist_trees = {} # dictionary of dictionaries
    for i in range(n_ver):
        # draw exp(beta)
        draw = np.random.exponential(scale=beta)
        deltas[i] = draw
    # calculate
    for i in range(n_ver): # v in V 
        dist = {}
        for j in range(n_ver): # u in V
            d = distances[(i,j)]
            arg = d - deltas[j]
            dist[j] = arg
        dist_trees[i] = dist
    
    for i in range(n_ver):
        current_list = clusters.get(i)
        # min dist
        dist = dist_trees[i]
        min_dist = min(dist)
        min_ver = dist.index(min_dist)
        if current_list==None:
            clusters[i] = [min_ver]
        else:
            current_list.append(min_ver)
            clusters[i] = current_list
 # return : clusters, spanning tree on each cluster rooted at its center
    return clusters, dist_trees
        

$(\epsilon, h, \epsilon)$ hopset: a set of edges E' such that
1. $|E'| \leq m'$
2. Each edge uv in E' corresponds to a uv-path in G suuch that $w(uv) = w(p)$
3. For any vertices u and v, with prob. 0.5 $dist^h_{E \cup E'} (u,v) \leq (1+\epsilon) dist_E(u,v)$.

Klein and Subramian approximates length of path can be found efficiently.

Our hop-set construction is based on recursive application of the exponential start time clustering
from Section 2.1. We will designate some of the clusters produced, specifically the larger ones, as
special. Since each vertex belongs to at most one cluster, there cannot be too many large clusters.
As a result we can afford to compute distances from their centers to all other vertices, and keep a
subset of them as hopset edges in the graph. There are two kinds of edges that we keep:
1. star edges between the center of a large cluster and all vertices in that cluster.
2. clique edges between the center of a large cluster and the centers of all other large clusters.

In other words, in building the hopset we put a star on top of each large cluster and connect their
centers into a clique. Then if our optimal s-t path $p^∗$
encounters two or more of these large clusters,
we can jump from the first to the last by going through their centers.

This allows us to replace what hopefully is a large part of p
∗ with only three edges: two star
edges and one clique edge. However this replacement may increase the length of the path by the
diameter of the large clusters. But as this distortion can only happen once, it is acceptable as long
as the diameter of the clusters are less than w(p
∗
). Our algorithm then recursively builds hopsets
on the small clusters. The probabilistic guarantees of an edge being cut gives that p
∗ does not
interact with too many such clusters.

2 parameters : beta with which decomp. routine run, and threshold $\rho$ by which cluster is too large

steps:

1. Compute a exponential start time clustering with parameter beta
2. Identify clusters with more than $n/\rho$ vertices as large clusters.
3. Construct star and clique edges from the centers of each large cluster.
4. Recurse on the small clusters.

goal: hopsets speed up parallel BFS

paralel : https://www.machinelearningplus.com/python/parallel-processing-python/#:~:text=In%20python%2C%20the%20multiprocessing%20module,in%20completely%20separate%20memory%20locations.



In [3]:
import multiprocessing as mp

In [ ]:
# algorithm 4

# application: hopsets -> shortest paths approximations with O(m poly log n) work

call= 0
def hopset(vertices, edges, beta, call):
    # compuute exp start time clust. with beta
    n_final = 3
    n = len(vertices)
    if len(vertices) < n_final:
        break
    exp_clustering, dist_trees =exp_start_time_cluster(g,beta,dist)
    if call==0:
        #pool = mp.Pool(mp.cpu_count())
        # for each cluster X
        for x in exp_clustering:
            newbeta = (k/eps)*(np.log(n))*beta
            hopset(x, x_edges, newbeta, call )
        #pool.close()
    else:
        # large and small cluusters sets
        thres = n/rho
        large_clusters = []
        small_clusters=[]
        for x in exp_clustering:
            # key is center of cluster : key is x
            xval = exp_clustering[x]
            size_xval = len(xval)
            if size_xval>=thres:
                large_clusters.append(x) # xval
                # add star edge btw center and all v in X with wt dist(v,c) -> matrix form ?
                for v in xval:
                    edges[v][x] = 1 # dist(v,c): min of dist_trees[v] and dist_trees[c] (?)
                    edges[x][v] = 1
                for v in xval:
                    # add edge
                
            else:
                small_clusters.append(x) # xval 
        # for all pairs of large clusters X_1, X_2 with centers c_1, c_2 add cliquue edge (c_1, c_2)
        for x1 in large_clusters:
            for x2 in large_clusters:
                # add to edges with weight dist(c1, c2)
                edges.append()
        # for each X in small clusters, recursively call HopSet in parallel 
        for x in small_clusters:
            out = hopset(vertices, edges, beta, call)
        
    # output: input graph G augmented with a set of weighted edge E*
    return edges
            

In [ ]:
# euler tour
# https://en.wikipedia.org/wiki/Euler_tour_technique


In [ ]:
# graph operator -> parameters -> features 


In [ ]:
# Phi_{k,n} operator has k-simplices of G as vertices
# 2 subgraphs are adjacent if they lie in common simplex with at most m vertices (pg. 136) 
# https://docs.scipy.org/doc/scipy/reference/generated/scipy.spatial.Delaunay.html

# k simplex is complex graph with k+1 vertices

all_cliques= nx.enumerate_all_cliques(g)

k = 3
m = 2
k_cliques=[x for x in all_cliques if len(x)== k+1 ]

# create new graph with vertex set k_cliques

# map from index to set
map1 = {}
map2 = {}
ind1=0

for x in k_cliques:
    map1[ind1] = x 
    map2[x] = ind1
    ind1= ind1+1

adj_mat = np.zeros((ind1,ind1))
# check adjacency up to m vertices

for c1 in k_cliques:
    for c2 in k_cliques:
        index1 = map2[c1]
        index2 = map2[c2]
        # compare lists for same elements
        if c1 == c2:
            continue
        counter1 = collections.Counter(c1)
        counter2 = collections.Counter(c2)
        set_list1 = set(tuple(d for d in sorted(counter1)))
        set_list2 = set(tuple(d for d in sorted(counter2)))
        intersect = set_list1.intersection(set_list2)
        ilen = len(intersect)
        if ilen> m:
            # add edge
            adj_mat[index1, index2] = 1
            adj_mat[index2, index1] = 1
            
            

In [ ]:
# pg 120 , middle graph
# intersection graph of all 1 or 2 simplices of G: edges and triangles
# Mid(G) = L(G \circ K_1 )

In [22]:
import pandas as pd
# https://machinelearningmastery.com/time-series-datasets-for-machine-learning/
shampoo = pd.read_csv("shampoo.csv", delimiter=",")

In [26]:
shampoo_y = shampoo["Sales"]

In [27]:
len(shampoo_y)

36

In [28]:
# array, 36 x 2
sham_x = range(36)

In [34]:
import numpy as np
sham_mat = np.zeros((36, 2))

In [35]:
sham_mat[:, 0] = sham_x
sham_mat[:,1] = shampoo_y

In [37]:
sham_mat[0]

array([  0., 266.])

In [30]:
sham = {'time' : sham_x, 'sales' : shampoo_y}
shampoo_df = pd.DataFrame(data=sham)
shampoo_df.head

<bound method NDFrame.head of     time  sales
0      0  266.0
1      1  145.9
2      2  183.1
3      3  119.3
4      4  180.3
5      5  168.5
6      6  231.8
7      7  224.5
8      8  192.8
9      9  122.9
10    10  336.5
11    11  185.9
12    12  194.3
13    13  149.5
14    14  210.1
15    15  273.3
16    16  191.4
17    17  287.0
18    18  226.0
19    19  303.6
20    20  289.9
21    21  421.6
22    22  264.5
23    23  342.3
24    24  339.7
25    25  440.4
26    26  315.9
27    27  439.3
28    28  401.3
29    29  437.4
30    30  575.5
31    31  407.6
32    32  682.0
33    33  475.3
34    34  581.3
35    35  646.9>

In [ ]:
# the time series turned into -> graph

# for t_c, yc with t_a < t_c < t_b, 
# y_c < y_b + (y_a - y_b) [ (t_b - t_c) / (t_b - t_a )]

for row in sham_mat:
    t_row = row[0]
    val_row = row[1]
    
    # 

edges = []
# faster way to check

total_len = len(sham_mat)
# fix y_a first 

for row_a in sham_mat:
    t_a = row_a[0]
    val_a = row_a[1]
    
    # iterate over y_b
    for ind_b in range(2, total_len):
        row_b = sham_mat[ind_b]
        
        t_b = row_b[0]
        val_b = row_b[1]
        
        bool_c = True
        
        for ind_c in range(1, ind_b):
            row_c = sham_mat[ind_c]
            
            t_c = row_c[0]
            val_c = row_c[1]
            
            if val_c < val_b and (val_a - val_b) > 0:
                # add edge
                edges.append((t_a, t_b))
                edges.append((t_b, t_a))
            else:
                # check condition
                if val_c < val_b + (val_a - val_b)*(t_b - t_c)/(t_b -t_a):
                    edges.append((t_a, t_b))
                    edges.append((t_b, t_a))
                
        

In [ ]:
# add features together


# features: max clique size
# touching number
# max degree
# degree distn 



In [ ]:

# (1) max clique size 

all_cliques= nx.enumerate_all_cliques(g)

clique_sizes = [len(x) for x in all_cliques ]

max_size = max(clique_sizes)

In [ ]:
# (3) max degree


# degree distn 


# sum up every column/row

In [ ]:
from sklearn.ensemble import AdaBoostClassifier
clf = AdaBoostClassifier(n_estimators=10)
clf.fit(train_x_sir, train_y)
pred_y = clf.predict(test_x_sir)
acc = accuracy_score(test_y, pred_y)
print(acc)

In [6]:
a = [1,2,3,4,5]

convert_tuple(a)

(1, 2, 3, 4, 5)

In [5]:
# edit to aggregate the labels
# April 6

# (1) aggregate node labels ( vertex histogram )

# (2) aggregate edge labels 

# Phi_{k,n} operator has k-simplices of G as vertices
# 2 subgraphs are adjacent if they lie in common simplex with at most n vertices (pg. 136) 
# https://docs.scipy.org/doc/scipy/reference/generated/scipy.spatial.Delaunay.html

# k simplex is complex graph with k+1 vertices

def convert_tuple(list):
    return tuple(i for i in list)


# assume labels are given from nodes 
labels_map = {1: [1,2], 2: [3,4], 3: [1,3]}

#edge_labels = {[1,2]:1, [3,4]:2}

def Phi(g, k,n, labels_map): # add labels_map arg 
    
    all_cliques= nx.enumerate_all_cliques(g)

    k_cliques=[x for x in all_cliques if len(x)== k+1 ]
    
    # must generate simplex of m vertices
    n_cliques = [x for x in all_cliques if len(x) <= n]

    # create new graph with vertex set k_cliques

    # map from index to set
    map1 = {}
    map2 = {} # backwards map
    ind1=0
    
    new_labels = {}

    for x in k_cliques:
        #print("x is", x)
        xtup = convert_tuple(x)
        map1[ind1] = x         
        map2[xtup] = ind1
        
        # aggregation of labels 
        label_list = []
        for vertex in x:
            vlabel = labels_map[vertex]
            label_list.append(vlabel) # extend(vlabel)
        new_labels[ind1] = label_list
        
        ind1= ind1+1

    adj_mat = np.zeros((ind1,ind1))
    new_edge_list = []

    # check adjacency up to m vertices
    ind1 =0
    ind2 = 0
    for c1 in k_cliques:
        for c2 in k_cliques:
            c1tup = convert_tuple(c1)
            c2tup = convert_tuple(c2)
            index1 = map2[c1tup]
            index2 = map2[c2tup]
            # compare lists for same elements
            if ind1== ind2:#c1 == c2:
                continue
            counter1 = collections.Counter(c1)
            counter2 = collections.Counter(c2)
            set_list1 = set(tuple(d for d in sorted(counter1)))
            set_list2 = set(tuple(d for d in sorted(counter2)))
            intersect = set_list1.intersection(set_list2)
            ilen = len(intersect)
            print("ilen is", ilen)
            # modification to the input of the operator: if there is n=1 or more vertices in common
            if ilen>= n:
                # add edge
                adj_mat[index1, index2] = 1
                adj_mat[index2, index1] = 1
                new_edge_list.append((index1, index2))
                new_edge_list.append((index2, index1))
                
                # check & aggregate edge labels ?
                
            ind2 = ind2+1
        ind1 = ind1+1

    return adj_mat, new_edge_list, k_cliques # 

TypeError: unhashable type: 'list'

In [10]:
from grakel.kernels import Kernel

from warnings import warn

from collections import Counter
from collections import Iterable

from grakel.graph import Graph

from numpy import zeros
from numpy import einsum
from numpy import array
from numpy import squeeze

from six import iteritems
from six import itervalues

In [35]:
# vertex histogram <-> phi_{k,n}

class vertex_phi(Kernel):
    
    def __init__(self, k=3, n= 10, n_jobs=None):
        super(vertex_phi, self).__init__(n_jobs=n_jobs)
        self.k = k
        self.n = n
    
    def _initialized(self):
        if not self._initialized["n_jobs"]:
            if self.n_jobs is not None:
                warn("hi")
            self._initialized["n_jobs"] = True
    
    def parse_input(self,X):
        # input is iterable with 1-3 features: adj mat / edge dictionary, node labels, edge labels
        # check input is iterable : if not isinstance(X, Iterable): raise TypeError("input must be iterable")
        
        rows, cols, data = list(), list(), list()
        
        self._method_calling = 1
        print("self method calling:", self._method_calling)
        
        if self._method_calling in [1,2]:
            labels = dict()
            self._labels = labels
        elif self._method_calling==3:
            labels= dict(self._labels)
        
        ni =0
        for (i, x) in enumerate(iter(X)):
            is_iter = isinstance(x, Iterable)
            if is_iter:
                x = list(x)
            if is_iter and len(x) in [0,2,3]:
                L = x[1]
            elif type(x) is Graph:
                L = x.get_labels(purpose="any")
            # construct data input for np array
            for (label, frequency) in iteritems(Counter(itervalues(L))):
                rows.append(ni)
                
                col_idx = labels.get(label, None)
                
                if col_idx is None:
                    col_idx = len(labels)
                    labels[label] = col_idx
                # designate column info
                cols.append(col_idx)
                
                # designate frequency value
                data.append(frequency)
            ni += 1
            
            
        # init the feature matrix
        
        features = zeros(shape=(len(X), len(labels)))
        features[rows, cols] = data
        
        return features

    def _calculate_kernel_matrix(self, Y=None):
        # calc kernel mat given target graph and kernel 
        if Y is None:
            K = self.X.dot(self.X.T)
        else:
            K = Y[:, :self.X.shape[1]].dot(self.X.T)
        
        return K 
    
    def diagonal(self):
        # calculate kernel matrix diagonal of fitted data
        self._X_diag = einsum('ij,ij->i', self.X, self.X)
        Y_diag = einsum('ij, ij->i', self._Y, self._Y)
        return self._X_diag, Y_diag
    


In [36]:
vp = vertex_phi()

In [20]:
# test vertex phi (histogram) kernel

H2o_adjacency = [[0,1,1],[1,0,0],[1,0,0]]
H2o_node_labels = {0: 'O', 1:'H', 2: 'H'}

H2O_graph = Graph(initialization_object = H2o_adjacency, node_labels=H2o_node_labels)

In [37]:
vp.parse_input((H2O_graph, H2O_graph))

self method calling: 1


array([[1., 2.],
       [1., 2.]])

In [7]:
import grakel

In [24]:
from grakel.kernels import VertexHistogram

In [25]:
vh = VertexHistogram()

In [29]:
vh.fit_transform((H2O_graph, H2O_graph))

array([[5., 5.],
       [5., 5.]])

In [3]:
lab = {1:2, 4:1, 5:1}
lab2 = [1,2,3,4]

In [2]:
dict(lab)

{1: 2, 4: 1, 5: 1}

In [4]:
dict(lab2)

TypeError: cannot convert dictionary update sequence element #0 to a sequence

In [ ]:
# def generate graphs ( WL_labels_inverse, nl)

# calc kernel matrix for 0 iteration 


# recalculate the labels
new_graphs = list()


# graph operator gives a way to aggregate vertex labels and edge labels


In [ ]:
# cycle basis 

In [ ]:
# how to combine edge + vertex kernels (w.r.t local Rademacher complexity ?)

# combine in subgraph matching ? https://github.com/ysig/GraKeL/blob/master/grakel/kernels/subgraph_matching.py


In [ ]:

def centrality(v, sp_mat):
    row = sp_mat[v]
    mn = np.mean(row)
    recip = 1/(mn)
    return recip

class ShortestPath(Kernel):

    _graph_bins = dict()

    def __init__(self, n_jobs=None,
                 normalize=False,
                 verbose=False,
                 with_labels=True,
                 algorithm_type="auto"):
        """Initialize a `shortest_path` kernel."""
        super(ShortestPath, self).__init__(
            n_jobs=n_jobs, normalize=normalize, verbose=verbose)

        self.with_labels = with_labels
        self.algorithm_type = algorithm_type
        self._initialized.update({"with_labels": False, "algorithm_type": False})
        
        

    def initialize(self):
        """Initialize all transformer arguments, needing initialization."""
        if not self._initialized["n_jobs"]:
            if self.n_jobs is not None:
                warnings.warn('no implemented parallelization for ShortestPath')
            self._initialized["n_jobs"] = True

        if not self._initialized["algorithm_type"]:
            if self.algorithm_type == "auto":
                self._graph_format = "auto"
            elif self.algorithm_type == "floyd_warshall":
                self._graph_format = "adjacency"
            elif self.algorithm_type == "dijkstra":
                self._graph_format = "dictionary"
            else:
                raise ValueError('Unsupported "algorithm_type"')

        if not self._initialized["with_labels"]:
            if self.with_labels:
                self._lt = "vertex"
                self._lhash = lhash_labels
                self._decompose_input = decompose_input_labels
            else:
                self._lt = "none"
                self._lhash = lhash
                self._decompose_input = decompose_input
    
    def parse_input(self, X):
        # returns sp_counts: dictionary for each vertex holds the counts of shortest path tuples
        
        # add: centrality : centrality scores of each vertex 
        i=0
        for (idx, x) in enumerate(iter(X)):
            if type(x) is Graph:
                spm_data = x.build_shortest_path_matrix(self.algorithm_type, labels=self._lt)
                
                centralities = {}
                # calculate centralities 
                for vertex in range(nvert):
                    cent = centrality(vertex, spm_data)
                    centralities[vertex] = cent
                
        S, L = self._decompose_input(spm_data)
                sp_counts[i] = dict()
                for u in range(S.shape[0]):
                    for v in range(S.shape[1]):
                        if u == v or S[u, v] == float("Inf"):
                            continue
                        label = self._lhash(S, u, v, *L)
                        if label not in self._enum:
                            if self._method_calling == 1:
                                idx = len(self._enum)
                                self._enum[label] = idx
                            elif self._method_calling == 3:
                                if label not in self._Y_enum:
                                    idx = len(self._enum) + len(self._Y_enum)
                                    self._Y_enum[label] = idx
                                else:
                                    idx = self._Y_enum[label]
                        else:
                            idx = self._enum[label]
                        if idx in sp_counts[i]:
                            sp_counts[i][idx] += 1
                        else:
                            sp_counts[i][idx] = 1
            

    def fit_transform(self, X, y=None):
        """Fit and transform, on the same dataset.
        Parameters
        ----------
        X : iterable
            Each element must be an iterable with at most three features and at
            least one. The first that is obligatory is a valid graph structure
            (adjacency matrix or edge_dictionary) while the second is
            node_labels and the third edge_labels (that fitting the given graph
            format).
        y : Object, default=None
            Ignored argument, added for the pipeline.
        Returns
        -------
        K : numpy array, shape = [n_targets, n_input_graphs]
            corresponding to the kernel matrix, a calculation between
            all pairs of graphs between target an features
        """
        self._method_calling = 2
        self.fit(X)

        # calculate feature matrices.
        phi_x = np.zeros(shape=(self._nx, len(self._enum)))

        for i in self.X.keys():
            for j in self.X[i].keys():
                phi_x[i, j] = self.X[i][j]

        # Transform - calculate kernel matrix
        self._phi_X = phi_x
        km = np.dot(phi_x, phi_x.T)

        self._X_diag = np.diagonal(km)
        if self.normalize:
            return np.divide(km, np.sqrt(np.outer(self._X_diag, self._X_diag)))
        else:
            return km

In [ ]:
# hierarchy defined by the random walk (?)

In [ ]:
# direct product graph of transformed graphs (?)

#https://networkx.org/documentation/networkx-1.10/reference/generated/networkx.algorithms.operators.product.cartesian_product.html

G = nx.Graph()
H = nx.Graph()

G.add_node(0,a1=True)
H.add_node('a',a2='Spam')
P = nx.cartesian_product(G,H)

In [ ]:
# compare G1 with G1 x G2 (dir product), G2 with G1 x G2 , add together the matrices in boolean way ?


In [ ]:
# optimal assignment of different boolean products/sums (?)

# based on different groupings of vertices (?)

In [4]:
bits=8
_max_number = 10
_mask = _max_number-1

In [6]:
# bit operation (try it out)
def ROT( n, d):
        """`rot` operation for binary numbers.
        Parameters
        ----------
        n : int
            The value which will be rotated.
        d : int
            The number of rotations.
        Returns
        -------
        rot : int
            The result of a rot operation.
        """
        m = d % bits

        if m > 0:
            return (n << m) & _mask | \
                   ((n & _mask) >> (bits-m))
        else:
            return n

In [13]:
ROT(5 ,3)

8

take direct product -> 
boolean multiplication (between original and dir product) 
-> optimal score ?


graph transform / grouping of vertices and edges -> subgraph kernel (combine edge and vertex) 

In [ ]:
# direct product of graphs

def direct_prod(g1, g2, v_labels1, v_labels2, e_labels1, e_labels2):
    
    n = len(g1)
    
    # first generate vertices (v1,v2) 
    vertices1x2 = {}
    inverse_vertices1x2= {}
    ind=0
    
    v1 = 0
    for lab1 in v_labels1:
        v2 = 0
        for lab2 in v_labels2:
            
            if lab1 == lab2:
                
                pair = (v1, v2)

                vertices1x2[ind] = pair
                inverse_vertices1x2[pair] = ind
            ind= ind+1
            v2 +=1
        v1+=1
            
    
    # iterate over adj matrices and edge lists 
    
    e_labels3 = np.zeros((n,n))
    
    g1_row = 0
    g2_row = 0
    for row1 in g1:
        for row2 in g2: 
            g1_col = 0
            g2_col = 0
            for e1 in row1:
                
                for e2 in row2:
                    
                    # check condition (u_1, u_2) in E1 and (v_1, v_2) in E2 and labele(u_1,u_2) = labele(v_1, v_2)
                    if e1 != 0:
                        if e2!=0:
                            # check label
                            label1 = e_labels1[g1_row, g1_col]
                            label2 = e_labels2[g2_row, g2_col]
                            
                            if label1==label2:
                                # add edge
                                v1 = inverse_vertices1x2[(g1_row, g1_col)]
                                v2 = inverse_vertices1x2[(g2_row, g2_col)]
                                e_labels3[v1, v2] = 1
                    
                    g2_col +=1
                g1_col+=1
            g2_row +=1
        g1_row +=1
                        
                    
# for efficiency, direct product of grouped vertices;



# group together vertices / edges based on closeness

# group together vertices / edges based on min wt cycle basis


# optimal assignment search based on (?) topological similarity


# independent sets based on being farther away from each other; start comparison between different groups

## compute the expander-ness of each group / set to compare 

topological similarity measure for proteins

topological measures of similarity

- bar visibility of a graph G: representation where each vertex is mapped to bar; any 2 vertices are connected in G iff corresponding bars have vertical line segment connecting them and intersects no other bar 

-> use also for visibility graphs

-- simple homotopy height

- searching (parameter) : how long to sweep a graph : node searching connection to homotopy height


--> tree-like ness? (how many cycles in basis divided by total # of leaves ?) 

https://z2pack.greschd.ch/en/latest/_downloads/75eec5bb13ab1589c8b65a3cc3781afd/z2pack_chapter.pdf

Calculating topological invariants with Z2Pack


In [ ]:
g1_row=0
    g2_row =0
    for row1 in g1:
        for row2 in g2:
            g1_col=0
            g2_col=0
            for e1 in row1:
                for e2 in row2:
                    lab1 = v_labels1[g1_row, g1_col]
                    lab2 = v_labels2[g2_row, g2_col]
                    if lab1==lab2:
                        pair = 
                    g2_col+=1
                g1_col+=1
            
            g2_row+=1
        g1_row+=1

In [ ]:
# kronecker prod yields homomorphism; https://en.wikipedia.org/wiki/Tensor_product_of_graphs

# what does boolean product yield?

In [ ]:
# breaking up the graph into different subgraphs / groups



In [ ]:
# A study of visibility graphs for time series representations

# properties: diameter d: max len of all shortest paths found
# btwn any pairs of nodes in (subgraph G' or graph G)

def diameter(g_shortest_paths_mat):
    return max(g_shortest_paths_mat)


In [ ]:
# properties: clustering coefficient (a study of visibility graphs for )

# for any node i, ratio of # of edges btwn its nbrs and # of possible edges

def clustering_coefficient(i, g): # node i in graph g (adj mat)
    # calculate number edges for each vertex
    n_edges=[]
    for row in g:
        n_edges.append(sum(row))
    
    # k_i nbrs 
    row_i = g[i]
    k_i = sum(row_i)
    # E_i : number of edges btwn i's nbrs
    E_i = 0
    ind = 0
    for el in row_i:
        if el== 1:
            n_current = n_edges[ind]
            E_i = E_i + n_current
        ind = ind+1
    C_i = 2*E_i/(k_i*(k_i-1))
    return C_i

In [14]:
gps = {}
gps[0] = [1]


In [15]:
for el in gps:
    print(el)

0


In [ ]:
# partition them by searching for leaves (degree 1 ) and vertices of degree 2 , slowly adding their neighbors to the group 

deg1v = []
deg2v = []

groups1 = {}
groups2 = {}
ind1 = 0
ind2 = 0

ind=0
for row in adj_mat:
	deg_row = sum(row)
	if deg_row==1:
		deg1v.append(ind)
        groups1[ind1] = ind
	if deg_row==2:
		deg2v.append(ind)
        groups2[ind2] = ind
    
	ind=ind+1
    

In [ ]:
# optimal assignment of groups based on these roots ; the groups may overlap : if they overlap, then use the 
# boolean product ? 

# propagate for k steps 
# from leaves 
n_groups = ind 
k = 5

for g in groups1:
    root = groups1[g]
    current_gp = [root]
    # extract the neighbors 
    row = np.array(adj_mat[root])
    nbrs = np.where(row == 1)
    current_gp.extend(nbrs)
    groups1[g] = current_gp 

# continue

for steps in range(k-1):
    # join the neighbors to the groups
    for g in groups1:
        roots = groups1[g] 
        current_gp = roots
        for r in roots:
            row = np.array(adj_mat[r])
            nbrs = np.where(row == 1)
            current_gp.extend(nbrs)
        groups1[g] = np.unique(current_gp)
    
# count the number of matching vertex or edge labels between the groups of the graphs

vertex_labels = [] # input 

vlab_map = {}

for g in groups1:
    v_labels = []
    for vertex in g:
        lab = vertex_labels[vertex]
        v_labels.append(lab)
    
    vlab_map[g] = v_labels

    

In [18]:
import numpy as np
w = np.array([1,2,3,4,5,4])
np.where(w == 4)

(array([3, 5]),)

In [19]:
np.unique(w)

array([1, 2, 3, 4, 5])

https://ysig.github.io/GraKeL/0.1a8/kernels/random_walk.html

performing random walk on directed graph is equivalent to performing a simultaneous random walk on G1 and G2


In [ ]:
# max entropy random walk

# trans prob defined in terms of components of eig centrality of node i 
# e_i is i-th component of normalized eigenvector corresponding to max eigenval of A 
