In [2]:
import grakel
import networkx as nx
import numpy as np

from grakel import Graph

In [3]:
edges_graph1 = {1:[2], 2:[1,3,4,5], 3:[2,4,6], 4:[2,3,5,6], 5:[2,4,6], 6:[3,4,5]}
edges_graph1_edge_diff= {1:[2,3], 2:[1,3,4,5], 3:[1,2,4,6], 4:[2,3,5,6], 5:[2,4,6], 6:[3,4,5]}

graph1 = Graph(edges_graph1)

graph1_copy = Graph(edges_graph1)

graph1_edge_diff = Graph(edges_graph1_edge_diff)

In [4]:
x = graph1.get_adjacency_matrix()

In [5]:
x1 = graph1_copy.get_adjacency_matrix()

In [6]:
y = graph1_edge_diff.get_adjacency_matrix()

In [7]:
x

array([[0., 1., 0., 0., 0., 0.],
       [1., 0., 1., 1., 1., 0.],
       [0., 1., 0., 1., 0., 1.],
       [0., 1., 1., 0., 1., 1.],
       [0., 1., 0., 1., 0., 1.],
       [0., 0., 1., 1., 1., 0.]])

In [19]:
# test the triangle graphs
edges_tri1 = {1:[2,3], 2:[1,3,4], 3:[1,2], 4:[2]}
edges_tri2 = {1:[2,3], 2:[1,3,4], 3:[1,2,4], 4:[2,3]}

tri1 = Graph(edges_tri1)
tri2 = Graph(edges_tri2)

# calculate for k= 3
atri1 = tri1.get_adjacency_matrix()
atri2 = tri2.get_adjacency_matrix()


In [24]:
atri2

array([[0., 1., 1., 0.],
       [1., 0., 1., 1.],
       [1., 1., 0., 1.],
       [0., 1., 1., 0.]])

In [20]:
atri1 

array([[0., 1., 1., 0.],
       [1., 0., 1., 1.],
       [1., 1., 0., 0.],
       [0., 1., 0., 0.]])

In [21]:
np.linalg.matrix_power(atri1, 2)

array([[2., 1., 1., 1.],
       [1., 3., 1., 0.],
       [1., 1., 2., 1.],
       [1., 0., 1., 1.]])

In [22]:
np.linalg.matrix_power(atri1, 3)

array([[2., 4., 3., 1.],
       [4., 2., 4., 3.],
       [3., 4., 2., 1.],
       [1., 3., 1., 0.]])

In [23]:
atri1+ np.linalg.matrix_power(atri1, 2) +np.linalg.matrix_power(atri1, 3)


array([[4., 6., 5., 2.],
       [6., 5., 6., 4.],
       [5., 6., 4., 2.],
       [2., 4., 2., 1.]])

In [8]:
# If A is an m × n matrix and B is a p × q matrix,
# then the Kronecker product A ⊗ B is the pm × qn block matrix:

print(len(x))
print(len(x[0]))

m=len(x)
n = len(x[0])

p = len(x1)
q = len(x1[0])

pm= p*m
qn= q*n

6
6


In [9]:
#ck = set(X.keys()) & (set(Y.keys()))
set(x.keys())

The history saving thread hit an unexpected error (OperationalError('database or disk is full')).History will not be written to the database.


AttributeError: 'numpy.ndarray' object has no attribute 'keys'

In [9]:
# double check how kroneck prod works
# Claculate Kronecker product matrix

# X,Y are tuples of adj matrices
X=x
Y=x1

ck = pm

XY = np.zeros(shape=(pm, qn))

xy_array = []

for k in range(6):
    
    XY += np.kron(X[k], Y[k])
    xy_array.append(np.kron(X[k], Y[k]))

# XY is a square matrix
s = XY.shape[0]

In [14]:
XYkron = np.kron(X,Y)

In [18]:
XYkron[10]

array([0., 1., 0., 1., 0., 1., 0., 0., 0., 0., 0., 0., 0., 1., 0., 1., 0.,
       1., 0., 1., 0., 1., 0., 1., 0., 1., 0., 1., 0., 1., 0., 0., 0., 0.,
       0., 0.])

In [13]:
s

36

In [14]:
XY

array([[1., 0., 1., ..., 2., 1., 3.],
       [1., 0., 1., ..., 2., 1., 3.],
       [1., 0., 1., ..., 2., 1., 3.],
       ...,
       [1., 0., 1., ..., 2., 1., 3.],
       [1., 0., 1., ..., 2., 1., 3.],
       [1., 0., 1., ..., 2., 1., 3.]])

In [10]:
xy_array[0]

array([0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0.])

In [11]:
xy_array[1]

array([1., 0., 1., 1., 1., 0., 0., 0., 0., 0., 0., 0., 1., 0., 1., 1., 1.,
       0., 1., 0., 1., 1., 1., 0., 1., 0., 1., 1., 1., 0., 0., 0., 0., 0.,
       0., 0.])

In [12]:
xy_array[2]

array([0., 0., 0., 0., 0., 0., 0., 1., 0., 1., 0., 1., 0., 0., 0., 0., 0.,
       0., 0., 1., 0., 1., 0., 1., 0., 0., 0., 0., 0., 0., 0., 1., 0., 1.,
       0., 1.])

In [ ]:
#if self.p is not None:

mu0 = 1

P = np.eye(XYkron.shape[0])
S = mu0 * P
for k in self.mu_[1:]:
    P = np.matmul(P, XYkron)
    S += k*P


In [ ]:
#if self.kernel_type == "geometric":
S_Geom = inv(np.identity(s) - self.lamda*XY).T
#elif self.kernel_type == "exponential":

S_exp = expm(self.lamda*XY).T
        

In [ ]:
# from random walk, parse input

def parse_input(self, X):
    """Parse and create features for graphlet_sampling kernel.
    Parameters
    ----------
    X : iterable
        For the input to pass the test, we must have:
        Each element must be an iterable with at most three features and at
        least one. The first that is obligatory is a valid graph structure
        (adjacency matrix or edge_dictionary) while the second is
        node_labels and the third edge_labels (that correspond to the given
        graph format). A valid input also consists of graph type objects.
    Returns
    -------
    out : list
        The extracted adjacency matrices for any given input.
    """
    if not isinstance(X, collections.Iterable):
        raise TypeError('input must be an iterable\n')
    else:
        i = 0
        proc = list()
        for (idx, x) in enumerate(iter(X)):
            is_iter = isinstance(x, collections.Iterable)
            if is_iter:
                x = list(x)
            if is_iter and len(x) in [1, 2, 3]:
                if len(x) == 0:
                    warnings.warn('Ignoring empty element' +
                                  ' on index: '+str(idx))
                    continue
                else:
                    x = Graph(x[0], x[1], {}, self._graph_format)
            elif type(x) is not Graph:
                raise TypeError('each element of X must be either a ' +
                                'graph or an iterable with at least 2 ' +
                                'and at most 3 elements\n')
            i += 1
            x.desired_format("adjacency")
            Ax = x.get_adjacency_matrix()
            Lx = x.get_labels(purpose="adjacency")
            Lx = [Lx[idx] for idx in range(Ax.shape[0])]
            proc.append((Ax, Lx, Ax.shape[0]))

        out = list()
        for Ax, Lx, s in proc:
            amss = dict()
            labels = set(Lx)
            Lx = np.array(Lx)
            for t in product(labels, labels):
                selector = np.matmul(np.expand_dims(Lx == t[0], axis=1),
                                     np.expand_dims(Lx == t[1], axis=0))
                amss[t] = Ax * selector
            out.append((amss, s))

        if i == 0:
            raise ValueError('parsed input is empty')

        return out